### ISSUE TITLE
saml login redirect to "remote/saml/login" not "sslvpn/portal.html"

### ISSUE THREAD

**Issue by urugang** [gm-vm/openfortivpn-webview#1]
hi, nice implementation, also your saml version openfortivpn.  

here is url changes in my saml auth. 
So it's better to remove "sslvpn/portal.html" limit.

also if we can store cookie for login.microsoftonline.com, user only need to auth only once.
```

https://remoteaccess.host.cc:20443/remote/saml/start
https://login.microsoftonline.com/122fd914-4f18-4efa-87bf-d1583939ff23/saml2?SAMLRequest=xxxx&RelayState=magic%3Dcd7e5d07eb24521e&SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1&Signature=yyyy
https://login.microsoftonline.com/122fd914-4f18-4efa-87bf-d1583939ff23/login
https://login.microsoftonline.com/common/SAS/ProcessAuth
https://login.microsoftonline.com/kmsi
cookie: SVPNCOOKIE, xxxxxxxxxxxxxxxxxxxx
https://remoteaccess.xx.cc:20443/remote/saml/login

```

**Comment by gm-vm** [comment]
The latest changes may be tailored for my usecase. I hoped `sslvpn/portal.html` was universal, but apparently it is not.

I can only have one active session at a time. If I try to login from two separate browsers, the second one will show me a prompt. This prompt tells me that there is already an active session and that if I choose to proceed by pressing its "continue" button, the other session will be closed. The same happens if I launch `openfortivpn-webview` twice in a row without logging out.

If there are no active sessions, this is what I get:
```
https://mygateway/remote/saml/start
https://XXXXXX.sso.duosecurity.com/login/?authkey=XXXX
https://YYYYYY.duosecurity.com/frame/frameless/v4/auth?sid=XXXX
https://YYYYYY.duosecurity.com/frame/v4/auth/prompt?sid=XXXX
https://XXXXXX.sso.duosecurity.com/duo/XXXX
SVPNCOOKIE=....     <-- I can use this right away
https://mygateway/remote/saml/login
https://mygateway/sslvpn/portal.html
SVPNCOOKIE=....     <-- Same exact cookie received earlier
```

This is what I get if there is an active session:
```
https://mygateway/remote/saml/start
https://XXXXXX.sso.duosecurity.com/login/?authkey=XXXX
https://YYYYYY.duosecurity.com/frame/frameless/v4/auth?sid=XXXX
https://YYYYYY.duosecurity.com/frame/v4/auth/prompt?sid=XXXX
https://XXXXXX.sso.duosecurity.com/duo/XXXX
SVPNCOOKIE=....    <-- This is not valid at this point
https://mygateway/remote/saml/login
https://mygateway/remote/loginconfirm     <-- This requires user interaction
https://mygateway/remote/loginconfirm?action=login
https://mygateway/sslvpn/portal.html
SVPNCOOKIE=....     <-- Same exact cookie received earlier
```

Do you have something similar? If not, I guess I need to have an extra command line argument to customize this behavior.

**Comment by gm-vm** [comment]
https://github.com/gm-vm/openfortivpn-webview/commit/a0f5935c036bb6167295126cb8048064a00e67f1 should fix your issue.

**Comment by urugang** [comment]
you are right. my vpn also redirect to "https://remoteaccess.xxxxx.cc:20443/sslvpn/portal.html#!/"

**Comment by gm-vm** [comment]
That's good to know, it makes me feel better about forcing the `--wait-url` behavior: https://github.com/gm-vm/openfortivpn-webview/commit/7d5c435b2f397e5d3f1f7b6aba6ce8e3141cc9d7

The main reason why I changed behavior once again is that I want to application to work properly by default.
The new log messages should make troubleshooting issues rather simple, but hopefully they won't be needed.
