### ISSUE TITLE
Electron appimage does not work on Ubuntu 24.04

### ISSUE THREAD

**Issue by jluquer** [gm-vm/openfortivpn-webview#37]
Hello!

I achieved to run it with tar.xz changing the chrome-sanbox permissions, but I am not able to run it with an AppImage. When I try to run the AppImage I get this error:

```
The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_openfonZ3pNN/chrome-sandbox is owned by root and has mode 4755.
```

**Comment by gm-vm** [comment]
It's probably this: https://github.com/electron/electron/issues/41066

Here a long discussion: https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844

You can either launch the application with `--no-sandbox` or temporarily disable the feature with: `sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0` (without `-w` the change is temporary and lost after reboot).

I'm not sure how this can be solved properly, given that an AppImage can be launched from anywhere and apparmor relies on paths. I saw xattrs mentioned in the issue, which would solve the path issue, but in any case there needs to be something in `/etc/apparmor.d` to make them effective.

**Comment by gm-vm** [comment]
The latest release (v1.2.3-electron) is also built as `.deb`, which should just work.

Since I still went down the AppArmor rabbit hole, I'm going to leave here some instructions.

---

If you want to use the AppImage you either have to use one of the commands of my previous message, or you can add an AppArmor profile.

You can do that in two ways, each with its own pros and cons.

### Path dependent
Create `/etc/apparmor.d/openfortivpn-webview` with the following content:
```
abi <abi/4.0>,
include <tunables/global>

profile openfortivpn-webview /PATH/TO/APPIMAGE flags=(unconfined) {
  userns,
}
```
where `/PATH/TO/APPIMAGE` is the absolute path to the executable. If you move the executable, you'll have to update the profile.

Then you can reload the profiles with the following command (you can also load just the profile with `apparmor_parser`):
```
sudo systemctl reload apparmor
```

### Path independent
Create `/etc/apparmor.d/openfortivpn-webview` with the following content:
```
abi <abi/4.0>,
include <tunables/global>

profile openfortivpn-webview /** xattrs=(security.apparmor=openfortivpn-webview) flags=(unconfined) {
  userns,
}
```

Then set the xattrs with:
```
sudo setfattr -h -n security.apparmor -v openfortivpn-webview /PATH/TO/APPIMAGE
```

If you download a new executable, you'll have to remember to set the xattrs.

Lastly, reload the profiles for the changes to take effect:
```
sudo systemctl reload apparmor
```
