### ISSUE TITLE
Blank white authentication (chrome) window pops-up

### ISSUE THREAD

**Issue by sfoxt1** [gm-vm/openfortivpn-webview#41]
When activating the openfortivpn using Linux Mint 22 on a 2011(?) Intel Macbook pro, the SSO authentication window opens with the electron install of openfortivpn-webview, and the fields are present because if I hover over the window the cursor changes. I can "invisibly" enter my email address, press <Enter>, enter my password, and I can see the terminal window accepting the inputs, but since the GUI window for the webview stays solid white, I cannot see the multifactor authentication number that pops up. The authenticator app on my phone activates so I know all the "code" is working, it's just the GUI window staying solid white that is stopping it from working correctly.

**Comment by gm-vm** [comment]
This is just a guess, but try to launch the application with `--disable-gpu` and see if anything changes. It has helped other users in the past.

Instead of disabling the GPU altogether you could use more specific `--disable-gpu-` options (I do not have a list, they are Chromium's flags), but finding what works is probably not worth the effort given that the browser just needs to run for few seconds.

**Comment by sfoxt1** [comment]
Thanks for the tip. I tried --disable-gpu and some more specific variants like --disable-accelerated-2d-canvas but none of them prevented the blank/white window.

**Comment by gm-vm** [comment]
I'm sorry, but I don't think I can help you here. Electron does the heavy lifting, this application just adds some listeners here and there to retrieve the session cookie.

You could either try to build the application using a different version of Electron (if you have some Electron based application that works you could try to figure out the version it uses) or you could try the Qt variant.

Building the Qt variant is quite easy, just clone the repo and follow this: https://github.com/gm-vm/openfortivpn-webview/tree/main/openfortivpn-webview-qt#how-to-build

Unfortunately each distro packages stuff differently, so I don't a list of dependencies, but in general you need the development files of `QtWebEngine` (the package is generally something like `qt6-qtwebengine-dev` or `qt6-qtwebengine-devel` or some other combination), `g++` and `make`. Hopefully these will pull all the other dependencies needed to build the application. qmake/cmake will otherwise tell you what you what is missing.

**Comment by gm-vm** [comment]
I'm closing this since I don't think there is anything I can do, but feel free to add more comments here.
